### ISSUE TITLE
help get data 

### ISSUE THREAD

**Issue by Sandy4321** [jgc128/mednli#1]
I do have a membership to physionet but still can not get data
https://physionet.org/works/MIMICIIIDerivedDataRepository/files/approved/mednli/

![image](https://user-images.githubusercontent.com/11426119/44994631-7b50f780-af6d-11e8-9702-9552002dcfb3.png)

**Comment by jgc128** [comment]
When happens if you open this url in an incognito window and click the link under the "Derived Data" section? 

https://physionet.org/physiotools/mimic-code/mednli/

**Comment by Sandy4321** [comment]
![image](https://user-images.githubusercontent.com/11426119/45001961-0945d600-afa0-11e8-89e5-ec2a48453efd.png)

![image](https://user-images.githubusercontent.com/11426119/45002030-99841b00-afa0-11e8-8a99-c6300163cbb1.png)

**Comment by Sandy4321** [comment]
but I alredy registered to phisionet

**Comment by Sandy4321** [comment]
maybe I need the special account to this https://mimic.physionet.org/gettingstarted/access/  ??

**Comment by Sandy4321** [comment]
for example not in this
http://it-claim.ru/Library/Books/Semantics_IT/gl1_2/glava1_2.htm#21

**Comment by Sandy4321** [comment]
and not in this
http://it-claim.ru/Library/Books/Semantics_IT/gl1_2/glava1_2.htm#22

**Comment by Sandy4321** [comment]
is it this
![image](https://user-images.githubusercontent.com/11426119/45002414-48762600-afa4-11e8-8b25-fcc54ab93b4b.png)

http://it-claim.ru/Library/Books/Semantics_IT/gl1_4/glava1_4.htm#41

**Comment by jgc128** [comment]
No, your PhysioNet account should work just fine. 
What happens if you press the "Sing In" button on the second screenshot [here](https://github.com/jgc128/mednli/issues/1#issuecomment-418196350)?

PS: Please go [here](https://github.com/jgc128/DefVectors/issues/10) regardless the question about the similarity

**Comment by jgc128** [comment]
Closing this - feel free to re-open if you still have the problem accessing the data.

**Comment by Sandy4321** [comment]
when go to link you provided, it again asks credentials
may you share data by another way than physio net?

**Comment by Sandy4321** [comment]
may be I should join your project 
![image](https://user-images.githubusercontent.com/11426119/46103731-95ae7780-c19f-11e8-881f-500dab4ab5b4.png)

**Comment by Sandy4321** [comment]
may be I should be member of this project
![image](https://user-images.githubusercontent.com/11426119/46103788-ba0a5400-c19f-11e8-9aa8-bf6690b0f79d.png)

**Comment by jgc128** [comment]
No, it should work without joining any project. Do you have access to MIMIC-III? Have you applied for it as described in the link you provided?

**Comment by Kyubyong** [comment]
I have the same issue. Strangely every time I access MIMIC, I fail to log in. After login, I can see nothing but such text as I don't belong to any projects, which is pretty frustrating.

**Comment by jgc128** [comment]
Have you done everything as suggested here https://mimic.physionet.org/gettingstarted/access/ ?

**Comment by Kyubyong** [comment]
Yes, I'm pretty sure.

**Comment by jgc128** [comment]
Are you able to download the MIMIC data itself?
